# Generated by Django 5.2.8 on 2025-11-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_id_remove_company_location_and_more'),
        ('users', '0003_remove_users_age_remove_users_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='users',
            name='authentication_type',
            field=models.CharField(blank=True, choices=[('Password', 'Password'), ('OAuth', 'Oauth'), ('SSO', 'Sso')], default='Password', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='language_preference',
            field=models.CharField(blank=True, default='en-US', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='time_zone',
            field=models.CharField(blank=True, default='UTC', max_length=50),
        ),
    ]
