# Generated by Django 5.2.8 on 2025-11-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_company_alter_users_authentication_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='company',
            new_name='companyId',
        ),
    ]
