# Generated by Django 5.2.8 on 2025-11-17 07:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_user', models.UUIDField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('industry', models.CharField(blank=True, max_length=120, null=True)),
                ('company_size', models.CharField(blank=True, max_length=120, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('time_zone', models.CharField(default='UTC', max_length=120)),
                ('language', models.CharField(default='en-US', max_length=50)),
                ('plan', models.CharField(default='starter', max_length=50)),
                ('lifecycle_status', models.CharField(choices=[('signup', 'Signup'), ('onboarding', 'Onboarding'), ('trial', 'Trial'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='signup', max_length=20)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('trial_start_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('workspace_limit', models.IntegerField(default=5)),
                ('storage_limit_mb', models.IntegerField(default=500)),
                ('products', models.JSONField(blank=True, null=True)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('monthly_ai_quota', models.IntegerField(default=1000)),
                ('ai_persona', models.JSONField(blank=True, null=True)),
                ('ai_memory_enabled', models.BooleanField(default=False)),
                ('data_sources', models.JSONField(blank=True, null=True)),
                ('ai_config', models.JSONField(blank=True, null=True)),
                ('security_mode', models.CharField(default='standard', max_length=50)),
                ('total_users', models.IntegerField(default=1)),
                ('active_users_last_30_days', models.IntegerField(default=0)),
                ('ai_interactions_month', models.IntegerField(default=0)),
                ('projects_count', models.IntegerField(default=0)),
                ('tasks_count', models.IntegerField(default=0)),
                ('created_via', models.CharField(default='web', max_length=50)),
                ('data_retention_days', models.IntegerField(default=365)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('last_security_review', models.DateTimeField(blank=True, null=True)),
                ('sso_enabled', models.BooleanField(default=False)),
                ('audit_logging_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'companies_company',
                'ordering': ['-created_date'],
            },
        ),
    ]
