# Generated by Django 5.2.8 on 2025-11-09 06:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('subscriptionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyId', models.UUIDField(blank=True, help_text='UUID of the company', null=True)),
                ('userId', models.UUIDField(blank=True, help_text='UUID of the user who created or owns the subscription', null=True)),
                ('plan', models.CharField(choices=[('Pro', 'Pro'), ('Max', 'Max'), ('Ultra Max', 'Ultra Max')], max_length=20)),
                ('billing_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=10)),
                ('license_count', models.PositiveIntegerField(default=1)),
                ('price_per_license', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled')], default='Inactive', max_length=10)),
                ('is_trial', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions_subscription',
            },
        ),
    ]
