# Generated by Django 5.2.8 on 2025-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='trial_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
