# Generated by Django 5.2.8 on 2025-11-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptions_trial_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
